// Generated by https://quicktype.io

export interface DespesaDTO {
  categoriaId: number;
  descricao:   string;
  notaFiscal:  NotaFiscal;
  projetoId:   number;
  valor:       number;
}

export interface NotaFiscal {
  dataDeEmissao: string;
  id:            number;
  linkDaImagem:  string;
}
